# Generated by Django 4.0.6 on 2022-07-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_deletedmovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieNames',
        ),
    ]
